# Generated by Django 3.0.6 on 2020-05-29 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('volume', models.IntegerField()),
                ('alcohol', models.BooleanField()),
                ('custom', models.BooleanField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('quantity_mu', models.CharField(max_length=20)),
                ('price_per_unit', models.FloatField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=60)),
                ('date', models.DateField(auto_now_add=True, max_length=60)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Cafe')),
                ('cocktails', models.ManyToManyField(to='myapi.Cocktail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_ingredient', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(to='myapi.CocktailIngredient'),
        ),
        migrations.CreateModel(
            name='CafeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=40)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='cocktail',
            field=models.ManyToManyField(to='myapi.Cocktail'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='ingredient',
            field=models.ManyToManyField(to='myapi.CafeIngredient'),
        ),
    ]
