# Generated by Django 3.0.6 on 2020-06-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
